import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Oliver Bunisess Cleaning Service",
  description: "Generated by create Claudio Silva Bispo",
};

import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      
      <body>
      <Navbar/>
        {children}
      <Footer/>
      </body>

    </html>
  );
}
